from django.urls import path
from . import views

urlpatterns=[

    path('',views.index,name='index'),
    path('studentlogin',views.studentlogin,name='studentlogin'),
    path('about',views.about,name='about'),
    path('addnewcourse',views.addnewcourse,name='addnewcourse'),
    path('adminlogin',views.adminlogin,name='adminlogin'),
    path('adminregi',views.adminregi,name='adminregi'),
    path('allstudent',views.allstudent,name='allstudent'),
    path('blank',views.blank,name='blank'),
    path('blog',views.blog,name='blog'),
    path('boxed',views.boxed,name='boxed'),
    path('breadcrumbs',views.breadcrumbs,name='breadcrumbs'),
    path('compact',views.compact,name='compact'),
    path('contact',views.contact,name='contact'),
    path('context',views.context,name='context'),
    path('coursecomment',views.coursecomment,name='coursecomment'),
    path('courses',views.courses,name='courses'),
    path('courseview',views.courseview,name='courseview'),
    path('dragula',views.dragula,name='dragula'),
    path('dropify',views.dropify,name='dropify'),
    path('events',views.events,name='events'),
    path('homes',views.homes,name='homes'),
    path('horizontal',views.horizontal,name='horizontal'),
    path('ind',views.ind,name='ind'),
    path('index2',views.index2,name='index2'),
    path('index3',views.index3,name='index3'),
    path('instruclogin',views.instruclogin,name='instruclogin'),
    path('instructreg',views.instructreg,name='instructreg'),
    path('message',views.message,name='message'),
    path('quiz',views.quiz,name='quiz'),
    path('studentreg',views.studentreg,name='studentreg'),
    path('layout',views.layout,name='layout'),
    path('shop',views.shop,name='shop'),
    path('sidebar',views.sidebar,name='sidebar'),
    path('teachers',views.teachers,name='teachers'),
    path('zoom',views.zoom,name='zoom'),
    path('indreg',views.indreg,name='indreg'),
    path('adreg',views.adreg,name='adreg'),
    path('insreg',views.insreg,name='insreg'),
    path('stureg',views.stureg,name='stureg'),
    path('boxedreg',views.boxedreg,name='boxedreg'),
    path('breadcrumbsreg',views.breadcrumbsreg,name='breadcrumbsreg'),
    path('contextreg',views.contextreg,name='contextreg'),
    path('zoomreg',views.zoomreg,name='zoomreg'),
    path('addnewreg',views.addnewreg,name='addnewreg'),
    
]